//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo.PlaceToPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargaMasivaMIDS
    {
        public long IDCargaMasivaMIDS { get; set; }
        public string Archivo { get; set; }
        public int CantidadRegistros { get; set; }
        public System.DateTime Fecha { get; set; }
        public int UsuarioID { get; set; }
        public string UbicacionRespaldo { get; set; }
    }
}
