//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo.PlaceToPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class MidsComercioPlaceToPay
    {
        public int IDMidsComerciosPlaceToPay { get; set; }
        public int IDComerciosPlaceToPay { get; set; }
        public string CodigoUnico { get; set; }
        public string MID { get; set; }
        public string Producto { get; set; }
        public string RUC { get; set; }
    }
}
