//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo.PlaceToPay
{
    using System;
    
    public partial class ReporteExcelMidsNuevosInfo
    {
        public string RUC { get; set; }
        public string Establecimiento { get; set; }
        public string Sector { get; set; }
        public string Dimension { get; set; }
        public string FechaAfiliacion { get; set; }
        public string RazonSocial { get; set; }
        public string NombreComercial { get; set; }
        public string DireccionComercio { get; set; }
        public string TelefonoCompleto1 { get; set; }
        public string IdentificacionRepresentanteLegal { get; set; }
        public string NombreRepresentanteLegal { get; set; }
        public string IdentificacionAdministrador { get; set; }
        public string NombresApellidosAdministrador { get; set; }
        public string NumeroCuentaBancaria { get; set; }
        public string TipoCuentaBancaria { get; set; }
        public string BancoCuentaBancaria { get; set; }
    }
}
