//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo.PlaceToPay
{
    using System;
    
    public partial class ReporteExcelMidsOperacionesInfo
    {
        public string RUC { get; set; }
        public string Establecimiento { get; set; }
        public string Especialidad { get; set; }
        public string Dimension { get; set; }
        public string FechaAfiliacion { get; set; }
    }
}
