//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo.PlaceToPay
{
    using System;
    
    public partial class TrackingComercioInfo
    {
        public string ID { get; set; }
        public string RUC { get; set; }
        public Nullable<System.DateTime> FechaContacto { get; set; }
        public string MID1 { get; set; }
        public string MID2 { get; set; }
        public string Producto { get; set; }
        public string Fase { get; set; }
        public string Observacion { get; set; }
    }
}
