//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo.PlaceToPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackingFasesComercio
    {
        public int IDTrackingFasesComercio { get; set; }
        public int ComercioPlaceToPayID { get; set; }
        public string RUC { get; set; }
        public int FaseID { get; set; }
        public string Observacion { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> ResponsableID { get; set; }
    }
}
